name: sgela_services
description: Shared code for SgelaAI.
version: 1.0.0
repository: https://github.com/malengatiger/sgela_services

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  cupertino_icons: ^1.0.6
  responsive_builder: ^0.7.0
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  firebase_messaging: ^14.7.19
  firebase_analytics: ^10.8.9
  firebase_crashlytics: ^3.4.18
  firebase_ui_auth: ^1.13.1
  firebase_ui_oauth_google: ^1.3.1
  firebase_storage: ^11.6.9
  cloud_firestore: ^4.15.8
  dio: ^5.4.1
  sqflite: ^2.3.2
  cached_network_image: ^3.3.1
  infinite_carousel: ^1.1.1
  intl: ^0.18.1
  path: ^1.8.3
  path_provider: ^2.1.2
  flutter_file_downloader: ^1.2.1
  get_it: ^7.6.7
  watch_it: ^1.4.0
  google_fonts: ^6.2.1
  mime: ^1.0.5
  shared_preferences: ^2.2.2
  play_integrity_flutter: ^0.0.1
  archive: ^3.4.10
  universal_io: ^2.2.2
  pinput: ^4.0.0
  intl_phone_field: ^3.2.0
  flutter_sim_country_code: ^0.1.2
  dots_indicator: ^3.0.0
  flutter_dotenv: ^5.1.0
  url_launcher: ^6.2.5
  flutter_analog_clock: ^1.0.3
  sms_autofill: ^2.3.1
  video_thumbnail: ^0.5.3
  page_transition: ^2.1.0
  universal_platform: ^1.0.0+1
  device_info_plus: ^9.1.2
  fluttertoast: ^8.2.4
  pretty_json: ^2.0.0
  google_maps_flutter: ^2.5.3
  image: ^4.1.7
  json_annotation: ^4.8.1
  flutter_tex: ^4.0.6
  flutter_local_notifications: ^16.3.3
  badges: ^3.1.2
  focused_menu: ^1.0.5
  carousel_slider: ^4.2.1
  http: ^1.2.0
  webview_flutter: ^4.7.0
  flutter_rating_bar: ^4.0.1
  image_picker: ^1.0.7
  share_plus: ^7.2.2
  flutter_markdown: ^0.6.18+3
  flutter_image_compress: ^2.1.0
  http_parser: ^4.0.2
  pdf: ^3.10.8
  printing: ^5.11.1
  flutter_gemini: ^2.0.3
  lottie: ^3.1.0
  dart_openai: ^5.1.0
  pin_code_fields: ^8.0.1
  reactive_forms: ^16.1.1
  geolocator: ^11.0.0
  geocoding: ^2.2.0
  permission_handler: ^11.3.0
  crypto: ^3.0.3
  convert: ^3.1.1
  flutter_staggered_grid_view: ^0.7.0
  markdown: ^7.2.2
  screenshot: ^2.1.0
  flutter_email_sender: ^6.0.2
  mailer: ^6.1.0
  google_generative_ai: ^0.2.2
  flutter_download_manager: ^0.5.5
  logger: ^2.1.0
  pay: ^2.0.0
  mistral_sgela_ai: ^1.1.0+2

  in_app_notification: ^1.1.2
  in_app_purchase: ^3.1.13
  in_app_purchase_storekit: ^0.3.13+1
  purchases_flutter: ^6.23.0

  pinecone: ^0.7.2
  langchain_pinecone: ^0.0.7
  langchain_google: ^0.2.4
  langchain_openai: ^0.4.1
  langchain_mistralai: ^0.0.3
  langchain: ^0.4.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  mockito: ^5.4.4
  json_serializable: ^6.7.1

